declare const styles: {
  readonly wrapper: string;
  readonly fieldAnchor: string;
  readonly labelRow: string;
  readonly label: string;
  readonly field: string;
  readonly error: string;
  readonly disabled: string;
  readonly bodyRow: string;
  readonly input: string;
  readonly tagsWrap: string;
  readonly valueText: string;
  readonly actions: string;
  readonly chevron: string;
  readonly chevronOpen: string;
  readonly slot: string;
  readonly errorIcon: string;
  readonly captionRow: string;
  readonly caption: string;
  readonly errorMessage: string;
  readonly optionHighlighted: string;
  readonly clearBtn: string;
  readonly tagsBelow: string;
  readonly overflowCount: string;
  readonly srOnly: string;
  readonly emptyState: string;
};
export default styles;
